### PR TITLE
Infinix HOT 3 LTE support

### PR DESCRIPTION
**Pull request by arizaini**
* cleanup subclasses and add some information

### CODE REVIEW

**Comment by osm0sis** [comment]
Hmm?

**Comment by arizaini** [comment]
Why sir? 😂 it's my bad, i just try if it conflict or not, so decided close it till my changes ready, I'm sorry for it

**Comment by osm0sis** [comment]
Haha okay. Please refrain from reformatting the entire repo. Just look at my YU Yuphoria commit for the only things required: https://github.com/osm0sis/boot-unlocker/commit/b81404bcc5f77be934c66ec5cf06b976af15961b

**Comment by arizaini** [comment]
Ok sir

**Pull request closed without merging**
